import Head from "next/head";

import {
  Banner,
  Category,
  ProductFeatured,
  ProductGrid,
  ProductMinimal,
  Testimonials,
} from "@/HomeSections";
import Sidebar from "@/HomeSections/Sidebar/index";
import Notification from "@/components/Notifications/Notification";
import Modal from "@/components/Modals/Modal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Notification />
      {/* <Modal /> */}
      <Banner />
      <Category />

      {/* 
    
-- PRODUCT CONTAINER

    */}

      <div className="product-container">
        <div className="container">
          <Sidebar />

          <div className="product-box">
            <ProductMinimal />
            <ProductFeatured />
            <ProductGrid />
          </div>
        </div>
      </div>
      {/* <Testimonials/>  */}
    </>
  );
}
